### ISSUE TITLE
Style the App Title

### ISSUE THREAD

**Issue by jeastgaard** [CMPUT301F22T32/Happy-Meals#26]
We want the app header to match the story point guis.

![Image](https://user-images.githubusercontent.com/82043671/195473307-c38fd09c-d023-447f-9df8-0ce7f174f695.png)

**Comment by BAFiogbe** [comment]
![Image](https://user-images.githubusercontent.com/68797818/199362874-371d4a9f-bfef-40d1-aa0a-87d3300c8056.png)
